# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 739)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView_ServiceProperty = QtWidgets.QListView(self.centralwidget)
        self.listView_ServiceProperty.setGeometry(QtCore.QRect(490, 60, 256, 192))
        self.listView_ServiceProperty.setObjectName("listView_ServiceProperty")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(528, 37, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.toolButton_OsServices = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_OsServices.setGeometry(QtCore.QRect(489, 29, 31, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/icons8-services.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_OsServices.setIcon(icon)
        self.toolButton_OsServices.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_OsServices.setObjectName("toolButton_OsServices")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 60, 311, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 269, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listView_ConfigFiles = QtWidgets.QListView(self.centralwidget)
        self.listView_ConfigFiles.setGeometry(QtCore.QRect(500, 299, 256, 192))
        self.listView_ConfigFiles.setObjectName("listView_ConfigFiles")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 519, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listView_ConfigFiles_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_ConfigFiles_2.setGeometry(QtCore.QRect(500, 540, 256, 141))
        self.listView_ConfigFiles_2.setObjectName("listView_ConfigFiles_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SUR.NET Settings tools"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open services windows</p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "Service property"))
        self.toolButton_OsServices.setToolTip(_translate("MainWindow", "Open services window"))
        self.toolButton_OsServices.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Current project "))
        self.label_3.setText(_translate("MainWindow", "Project config files:"))
        self.label_4.setText(_translate("MainWindow", "Project process:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
