# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(25, 25))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView_ServiceProperty = QtWidgets.QListView(self.centralwidget)
        self.listView_ServiceProperty.setGeometry(QtCore.QRect(490, 60, 256, 192))
        self.listView_ServiceProperty.setObjectName("listView_ServiceProperty")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(528, 37, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.toolButton_OsServices = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_OsServices.setGeometry(QtCore.QRect(489, 29, 31, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/Role.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_OsServices.setIcon(icon)
        self.toolButton_OsServices.setObjectName("toolButton_OsServices")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SUR.NET Settings tools"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open services windows</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Service property"))
        self.toolButton_OsServices.setToolTip(_translate("MainWindow", "Open services window"))
        self.toolButton_OsServices.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
